#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Private Plugin System

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."
pnpm install

echo ""
echo "Installing plugin system dependencies..."
pnpm add simple-git octokit
pnpm add -D @types/simple-git

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Auto Claude UI (Electron + Vite)..."
npm run dev &

# Wait for Vite dev server
wait_for_service 3000 "Vite Dev Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Auto Claude UI: http://localhost:3000"
echo "  Electron: Desktop app window should open automatically"
echo ""
echo "Plugin Directory:"
echo "  ~/.auto-claude/plugins/ (will be created on first run)"
echo ""
echo "Next Steps:"
echo "  1. Wait for Electron window to open"
echo "  2. Open Settings → Plugins tab"
echo "  3. Install the Quik Nation boilerplate plugin"
echo "  4. Add a boilerplate project to test detection"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""
