#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Plugin Manifest Schema task

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting main service (TypeScript/React/Electron)..."
echo ""

# Main service (development mode)
# Get the project root relative to this script
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/../../.." && pwd )"
cd "$PROJECT_ROOT"
npm run dev &
wait_for_service 3000 "Main Application"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Main Application: http://localhost:3000"
echo ""
echo "Development Info:"
echo "  Package Manager: pnpm"
echo "  Build Tool: Vite"
echo "  Testing: Vitest"
echo "  State Management: Zustand"
echo ""
echo "Available Commands:"
echo "  npm run dev         - Start development server"
echo "  npm run test        - Run unit tests"
echo "  npm run lint        - Run linter"
echo "  npx tsc --noEmit    - Type check without emitting"
echo ""
